'use client';

import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cardThemes } from '@/components/wrapped';

// All card templates
import {
    IntroCard,
    StatsOverviewCard,
    TimeSpentCard,
    MostActiveMonthCard,
    ChannelSpotlightCard,
    TopChannelsCard,
    WatchCycleCard,
    DayOfWeekCard,
    LongestStreakCard,
    PersonalityCard,
    BingeSessionsCard,
    LateNightCard,
    HabitsCard,
    PatternsCard,
    RewatchedCard,
    SubscriptionCard,
    SearchInsightsCard,
    FirstLastVideoCard,
    OutroCard,
} from '@/components/wrapped/card-templates';

/**
 * YouTube Wrapped Demo v2
 * Full 19-card flow based on cards_doc.md specification
 *
 * The demo is generated by the backend from committed seed data, running the same
 * pipeline as a real upload rather than hardcoding card values here. If the pipeline
 * changes, the demo changes with it.
 */

export default function WrappedDemoPage() {
    const [currentCard, setCurrentCard] = useState(0);

    const [api, setApi] = useState<any | null>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
        fetch(`${apiUrl}/api/wrapped/demo`)
            .then((res) => {
                if (!res.ok) throw new Error('Could not load the demo');
                return res.json();
            })
            .then(setApi)
            .catch((e) => setError(e instanceof Error ? e.message : 'Could not load the demo'));
    }, []);

    if (error) {
        return (
            <div className="flex flex-col items-center justify-center min-h-screen px-4 text-center">
                <p className="text-lg font-medium mb-2">The demo could not be loaded</p>
                <p className="text-sm text-muted-foreground">{error}</p>
            </div>
        );
    }

    if (!api) {
        return (
            <div className="flex flex-col items-center justify-center min-h-screen px-4">
                <Loader2 className="w-12 h-12 animate-spin text-purple-500 mb-4" />
                <p className="text-muted-foreground">Loading the demo Wrapped...</p>
            </div>
        );
    }

    // Everything below comes from the backend pipeline; only the display name is a
    // demo flourish, since the pipeline has no name to read from a Takeout export.
    const demoData = {
        username: 'Explorer',
        year: api.intro.year,

        videosWatched: api.stats_overview.videos_watched,
        channelsExplored: api.stats_overview.channels_explored,
        activeDays: api.stats_overview.active_days,
        totalSessions: api.stats_overview.total_sessions,

        totalHours: api.time_spent.total_hours,
        totalMinutes: api.time_spent.total_minutes,
        avgDailyMinutes: api.time_spent.avg_daily_minutes,

        peakMonth: api.peak_month.month,
        peakMonthWatches: api.peak_month.watches,

        topChannel: api.top_channel,
        topChannels: api.top_channels.channels,

        peakHour: api.watch_cycle.peak_hour,
        hourlyData: api.watch_cycle.hourly_data,
        peakDay: api.peak_day.day,
        longestStreak: api.longest_streak.days,
        streakDates: api.longest_streak.dates,

        personalityType: api.personality.type,
        personalityDescription: api.personality.description,

        totalBinges: api.binge_sessions.count,
        longestBingeDuration: api.binge_sessions.longest_duration,
        longestBingeDate: api.binge_sessions.longest_date,

        lateNightVideos: api.late_night.videos,
        latestWatch: api.late_night.latest_time,
        latestWatchDate: api.late_night.latest_date,

        habitChannels: api.habits.total_channels,
        strongestHabit: api.habits.strongest,

        patterns: {
            totalPatterns: api.patterns.total_patterns,
            insights: api.patterns.insights,
        },

        rewatchedCount: api.rewatched.count,
        topRewatched: api.rewatched.top_video,
        rewatchTimes: api.rewatched.top_times,

        totalSubscriptions: api.subscriptions.total,
        watchedSubscribed: api.subscriptions.watched,
        overlapPercentage: api.subscriptions.overlap_percentage,
        ghostSubscriptions: api.subscriptions.ghost,

        totalSearches: api.searches.total,
        topSearch: api.searches.top_search,

        firstVideo: api.first_last.first_video,
        lastVideo: api.first_last.last_video,
    };

    // Section labels for navigation
    const sections = [
        { name: 'INTRO', startIndex: 0 },
        { name: 'YOUR YEAR', startIndex: 1 },
        { name: 'FAVORITES', startIndex: 4 },
        { name: 'RHYTHM', startIndex: 6 },
        { name: 'PERSONALITY', startIndex: 10 },
        { name: 'DEEP DIVES', startIndex: 11 },
        { name: 'OUTRO', startIndex: 18 },
    ];

    // All cards in order
    const cards = [
        // SECTION 1: INTRO (index 0)
        <IntroCard key="intro" username={demoData.username} year={demoData.year} />,

        // SECTION 2: YOUR YEAR WITH US (indices 1-3)
        <StatsOverviewCard
            key="stats"
            videosWatched={demoData.videosWatched}
            channelsExplored={demoData.channelsExplored}
            activeDays={demoData.activeDays}
            totalSessions={demoData.totalSessions}
        />,
        <TimeSpentCard
            key="time"
            totalHours={demoData.totalHours}
            totalMinutes={demoData.totalMinutes}
            avgDailyMinutes={demoData.avgDailyMinutes}
        />,
        <MostActiveMonthCard
            key="peak-month"
            peakMonth={demoData.peakMonth}
            peakMonthWatches={demoData.peakMonthWatches}
        />,

        // SECTION 3: YOUR FAVORITES (indices 4-5)
        <ChannelSpotlightCard
            key="spotlight"
            channelName={demoData.topChannel.name}
            totalViews={demoData.topChannel.views}
            percentageOfTotal={demoData.topChannel.percentage}
        />,
        <TopChannelsCard key="top-channels" channels={demoData.topChannels} />,

        // SECTION 4: YOUR RHYTHM (indices 6-9)
        <WatchCycleCard
            key="watch-cycle"
            peakHour={demoData.peakHour}
            hourlyData={demoData.hourlyData}
        />,
        <DayOfWeekCard key="day-of-week" peakDay={demoData.peakDay} />,
        <LongestStreakCard
            key="streak"
            streakDays={demoData.longestStreak}
            streakDates={demoData.streakDates}
        />,

        // SECTION 5: PERSONALIZATION (index 10)
        <PersonalityCard
            key="personality"
            personalityType={demoData.personalityType}
            description={demoData.personalityDescription}
        />,

        // SECTION 6: DEEP DIVES (indices 11-17)
        <BingeSessionsCard
            key="binge"
            totalBinges={demoData.totalBinges}
            longestDuration={demoData.longestBingeDuration}
            longestDate={demoData.longestBingeDate}
        />,
        <LateNightCard
            key="late-night"
            lateNightVideos={demoData.lateNightVideos}
            latestWatch={demoData.latestWatch}
            latestWatchDate={demoData.latestWatchDate}
        />,
        <HabitsCard
            key="habits"
            totalHabitChannels={demoData.habitChannels}
            strongestHabit={demoData.strongestHabit}
        />,
        <PatternsCard
            key="patterns"
            totalPatterns={demoData.patterns.totalPatterns}
            insights={demoData.patterns.insights}
        />,
        <RewatchedCard
            key="rewatched"
            rewatchedCount={demoData.rewatchedCount}
            topRewatched={demoData.topRewatched}
            rewatchTimes={demoData.rewatchTimes}
        />,
        <SubscriptionCard
            key="subscriptions"
            totalSubscriptions={demoData.totalSubscriptions}
            watchedSubscribed={demoData.watchedSubscribed}
            overlapPercentage={demoData.overlapPercentage}
            ghostSubscriptions={demoData.ghostSubscriptions}
        />,
        <SearchInsightsCard
            key="search"
            totalSearches={demoData.totalSearches}
            topSearch={demoData.topSearch}
        />,
        <FirstLastVideoCard
            key="first-last"
            firstVideoTitle={demoData.firstVideo.title}
            firstVideoDate={demoData.firstVideo.date}
            lastVideoTitle={demoData.lastVideo.title}
            lastVideoDate={demoData.lastVideo.date}
        />,

        // SECTION 7: OUTRO (index 17)
        <OutroCard key="outro" year={demoData.year} />,
    ];

    const goNext = () => setCurrentCard((c) => (c + 1) % cards.length);
    const goPrev = () => setCurrentCard((c) => (c - 1 + cards.length) % cards.length);

    // Get current section
    const getCurrentSection = () => {
        for (let i = sections.length - 1; i >= 0; i--) {
            if (currentCard >= sections[i].startIndex) {
                return sections[i].name;
            }
        }
        return sections[0].name;
    };

    return (
        <div className="min-h-screen bg-background flex flex-col items-center justify-center p-4">
            {/* Header */}
            <div className="text-center mb-6">
                <h1 className="text-2xl font-bold text-foreground mb-1">
                    YouTube Wrapped Demo
                </h1>
                <div className="flex items-center justify-center gap-3">
                    <span className="px-3 py-1 bg-purple-500/20 text-purple-400 rounded-full text-sm">
                        {getCurrentSection()}
                    </span>
                    <span className="text-muted-foreground text-sm">
                        Card {currentCard + 1} of {cards.length}
                    </span>
                </div>
            </div>

            {/* Card Display */}
            <div className="relative flex items-center gap-4">
                <Button
                    variant="ghost"
                    size="icon"
                    onClick={goPrev}
                    className="text-white hover:bg-white/10"
                >
                    <ChevronLeft className="w-8 h-8" />
                </Button>

                <div className="transition-all duration-300 transform hover:scale-[1.02]">
                    {cards[currentCard]}
                </div>

                <Button
                    variant="ghost"
                    size="icon"
                    onClick={goNext}
                    className="text-white hover:bg-white/10"
                >
                    <ChevronRight className="w-8 h-8" />
                </Button>
            </div>

            {/* Section indicators */}
            <div className="flex gap-1 mt-6">
                {sections.map((section, i) => {
                    const nextSectionStart = sections[i + 1]?.startIndex ?? cards.length;
                    const cardsInSection = nextSectionStart - section.startIndex;
                    const isActive = currentCard >= section.startIndex && currentCard < nextSectionStart;

                    return (
                        <button
                            key={section.name}
                            onClick={() => setCurrentCard(section.startIndex)}
                            className={`h-2 rounded-full transition-all ${isActive
                                ? 'bg-white w-8'
                                : 'bg-white/30 hover:bg-white/50 w-4'
                                }`}
                            title={section.name}
                        />
                    );
                })}
            </div>

            {/* Dot indicators */}
            <div className="flex gap-1.5 mt-4">
                {cards.map((_, i) => (
                    <button
                        key={i}
                        onClick={() => setCurrentCard(i)}
                        className={`w-2 h-2 rounded-full transition-all ${i === currentCard
                            ? 'bg-white scale-125'
                            : 'bg-white/20 hover:bg-white/40'
                            }`}
                    />
                ))}
            </div>

            {/* Theme showcase */}
            <div className="mt-8 text-center">
                <h2 className="text-sm font-semibold text-white/50 mb-2">Available Themes</h2>
                <div className="flex gap-2 flex-wrap justify-center max-w-md">
                    {Object.keys(cardThemes).map((theme) => (
                        <div
                            key={theme}
                            className={`px-3 py-1 rounded-full text-xs font-medium ${cardThemes[theme as keyof typeof cardThemes].bg
                                } ${cardThemes[theme as keyof typeof cardThemes].text}`}
                        >
                            {theme}
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
